include:
  local: ci/install-rkorapclient-ci.yml

test-korapclient:
  extends: .install-rkorapclient
  image: rocker/tidyverse
  cache:
    key: pykorapclient
    paths:
    - apt-cache/

  script:
    - mkdir -p ~/.config/pip
    - echo -e "[global]\nbreak-system-packages = true" >> ~/.config/pip/pip.conf
    - python3 -m pip install pytest
    - export LD_LIBRARY_PATH=$(dirname $(find / -name libR.so)):$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - python3 -m pip install .
    - python3 -m pytest -v
