include:
  local: ci/install-rkorapclient-ci.yml

test-korapclient-on-latest:
  extends: .install-rkorapclient
  image: ubuntu:latest
  cache:
    key: rkorapclient-ubuntu-stable
    paths:
    - apt-cache/
    - ccache/
    - rlib/
  script:
    - mkdir -p ~/.config/pip
    - echo -e "[global]\nbreak-system-packages = true" >> ~/.config/pip/pip.conf 
    - python3 -m pip install .
    - python3 -m pytest -v

